In [1]:
import numpy as np 

## numpy array

In [2]:
benimListem = [10,20,30]

In [3]:
type(benimListem)

list

In [5]:
np.array(benimListem)

array([10, 20, 30])

In [6]:
matrixListem = [[10,20,30] , [40,50,60] , [70,80,90]]

In [7]:
np.array(matrixListem)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## arange

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [12]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## linspace

In [13]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## eye

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random

In [15]:
np.random.randn(4)

array([ 1.66077037, -0.16839453,  0.1252572 ,  0.24031658])

In [16]:
np.random.randn(4,4)

array([[ 1.41261455, -0.64100868,  1.80390958, -0.15236821],
       [-1.5792813 , -1.06858868, -1.31542027,  0.78653887],
       [ 0.00195158, -0.57437645,  1.45882409,  0.3298318 ],
       [ 1.85014249,  0.27216529, -0.03564373,  0.56019325]])

In [17]:
np.random.randint(1,10)

6

In [18]:
np.random.randint(1,10,5)

array([2, 5, 3, 6, 4])

## numpy dizi metodları

In [21]:
benimNumpyDizim = np.arange(0,30)

In [22]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
benimRandomDizim = np.random.randint(0,100,20)

In [24]:
benimRandomDizim

array([69, 96, 44, 57, 66, 64, 23, 69, 75, 90,  4, 45, 92, 73, 64, 44, 67,
       36, 90, 56])

In [25]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [26]:
benimRandomDizim.max()

96

In [27]:
benimRandomDizim.min()

4

In [28]:
benimRandomDizim.argmax() #bu sayede en büyük elemanın kaçıncı indexte olduğunu gösterir

1

In [30]:
benimReshapeDizim = benimRandomDizim.reshape(5,4)

In [31]:
benimReshapeDizim

array([[69, 96, 44, 57],
       [66, 64, 23, 69],
       [75, 90,  4, 45],
       [92, 73, 64, 44],
       [67, 36, 90, 56]])

In [32]:
benimReshapeDizim.shape

(5, 4)

In [33]:
benimDizim = np.arange(0,15)

In [34]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
benimDizim[5]

5

In [36]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [37]:
benimDizim[2:5] = -3

In [38]:
benimDizim

array([ 0,  1, -3, -3, -3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
baskaDizi = np.arange(0,24)

In [40]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [41]:
slicingDizisi = baskaDizi[3:8]

In [42]:
slicingDizisi

array([3, 4, 5, 6, 7])

In [43]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
slicingDizisi[:] = 123

In [45]:
slicingDizisi

array([123, 123, 123, 123, 123])

In [46]:
baskaDizi

array([  0,   1,   2, 123, 123, 123, 123, 123,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [47]:
ornekDizi = np.arange(0,24)

In [48]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [49]:
ornekDiziKopyası = ornekDizi.copy()

In [50]:
ornekDiziKopyası[:] = 9

In [51]:
ornekDiziKopyası

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9])

In [52]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [53]:
benimListem = [[10,20,30] , [30,40,50] , [50,60,70]]

In [54]:
benimMatrixDizim = np.array(benimListem)

In [55]:
benimListem

[[10, 20, 30], [30, 40, 50], [50, 60, 70]]

In [56]:
benimMatrixDizim

array([[10, 20, 30],
       [30, 40, 50],
       [50, 60, 70]])

In [57]:
benimMatrixDizim[0]

array([10, 20, 30])

In [59]:
benimMatrixDizim[0][1]

20

In [60]:
benimMatrixDizim[1,2]

50

In [61]:
benimMatrixDizim[1:,2]

array([50, 70])

In [63]:
yeniListem = [[10,20,30,40,50],[60,70,80,90,100],[110,120,130,140,150] , [160,170,180,190,200]]

In [64]:
yeniMatrix = np.array(yeniListem)

In [65]:
yeniMatrix

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [69]:
yeniMatrix[[1,3,2]]

array([[ 60,  70,  80,  90, 100],
       [160, 170, 180, 190, 200],
       [110, 120, 130, 140, 150]])

## operasyonlar

In [72]:
yeniBirDizi = np.random.randint(0,100,20)

In [73]:
yeniBirDizi

array([70, 36,  1, 15,  1, 14, 40, 31, 81, 85, 13, 92, 13, 19, 54, 86, 35,
       72, 21, 73])

In [74]:
yeniBirDizi >30

array([ True,  True, False, False, False, False,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True])

In [75]:
sonucDizisi = yeniBirDizi > 20

In [76]:
sonucDizisi

array([ True,  True, False, False, False, False,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
        True,  True])

In [77]:
yeniBirDizi[sonucDizisi]

array([70, 36, 40, 31, 81, 85, 92, 54, 86, 35, 72, 21, 73])

In [78]:
yeniBirDizi[yeniBirDizi>40]

array([70, 81, 85, 92, 54, 86, 72, 73])

In [79]:
sonDizi = np.arange(0,24)

In [80]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [81]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [82]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [83]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [84]:
sonDizi / sonDizi

C:\Users\emirh\AppData\Local\Temp\ipykernel_10692\1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [85]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [86]:
np.max(sonDizi)

23

In [87]:
np.min(sonDizi)

0